@startuml

participant VirtualMainView #white
participant MainServerActions #yellow

VirtualMainView -> MainServerActions: connect(this, currentUser)
MainServerActions -> VirtualMainView: sendLobbies(): []
VirtualMainView -> MainServerActions: send(new JoinLobbyCommand(1))
MainServerActions -> VirtualMainView: sendError("Invalid lobby id")
VirtualMainView -> MainServerActions: send(new CreateLobbyCommand)
MainServerActions -> VirtualMainView: sendLobbies(): [(id: 1, manager: currentUser, users: [currentUser], gamestarted: false)]
note over MainServerActions: anotherUser joins the lobby
MainServerActions -> VirtualMainView: sendLobbies(): [(id: 1, manager: currentUser, users: [currentUser, anotherUser], gamestarted: false)]
VirtualMainView -> MainServerActions: joinGame(currentUser): connectionInfo
MainServerActions -> VirtualMainView: sendLobbies(): [(id: 1, manager: currentUser, users: [currentUser, anotherUser], gamestarted: true)]
note across: the user can now open the game connection with the information in the received connectionInfo object
@enduml