@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class AccountScene
class ActionCache
class CLI
class CLICardUtils
class CLICommand
class CLIPrinter
class Card
enum CardSide << enumeration >>
class CardsPlayabilityEvent
class ChosenObjectiveCardEvent
class ChosenStarterCardSideEvent
class Client
class Command
class CommandConsumer<Command>
class Config
class ConfigController
class ConnectionCommand
class ConnectionHandler
class ConnectionLostScene
class ConnectionScene
class Controller
class Coords
class Corner
enum CornerPosition << enumeration >>
enum CornerTypes << enumeration >>
class CreateGameMenu
class CreateLobbyCommand
class CreateLobbyError
class Deck<CardType>
class Decks
class DirectMessageCommand
class DirectMessageEvent
class DrawCardState
class DrawGoldDeckCardCommand
class DrawObjectiveCardsCommand
class DrawResourceDeckCardCommand
class DrawStarterCardCommand
class DrawVisibleGoldCardCommand
class DrawVisibleResourceCardCommand
class DrawnGoldDeckCardEvent
class DrawnObjectiveCardsEvent
class DrawnResourceDeckCardEvent
class DrawnStarterCardEvent
class DrawnVisibleGoldCardEvent
class DrawnVisibleResourceCardEvent
interface Elements << interface >>
class EndedInitializationPhaseEvent
class EndedObjectiveCardPhaseEvent
class EndedStarterCardPhaseEvent
class EndedTokenPhaseEvent
class EndingGameInitScene
class Event
class GUI
class GameCommand
class GameController
class GameErrorEvent
class GameEvent
interface GameEventHandler << interface >>
class GameFlowManager
class GameModel
class GameModelUpdater
class GameResultsEvent
class GameScene
interface GameServerActions << interface >>
class GameStartedEvent
class GameState
interface GameViewActions << interface >>
class GoldCard
class GoldDeckCreator
class GroupMessageCommand
class GroupMessageEvent
class HomeScene
class InitializationState
enum Items << enumeration >>
class ItemsObjectiveStrategy
class JoinGameMenu
class JoinLobbyCommand
class JoinLobbyController
class JoinLobbyError
class KeepAliveCommand
class KeepAliveEvent
class LastConnectedPlayerEvent
class LastConnectedPlayerWonEvent
class LastPlayerScene
class LastPlayerWonScene
class LastRoundEvent
class LeaveLobbyCommand
class LeaveLobbyError
class LightGoldCard
class LightResourceCard
class LightStarterCard
class LobbiesEvent
class LobbiesListController
class LobbiesScene
class Lobby
class LobbyController
class LobbyInfo
class LoginEvent
class MainCommand
class MainController
class MainErrorEvent
class MainEvent
interface MainEventHandler << interface >>
interface MainServerActions << interface >>
interface MainViewActions << interface >>
class MenuController
class MessageCommand
class MessageEvent
class ObjectiveCard
class ObjectiveCardScene
class ObjectiveCardSelectionState
class ObjectiveDeckCreator
interface ObjectiveStrategy << interface >>
class Observable
interface Observer << interface >>
class Pair<T1, T2>
class PatternObjectiveStrategy
class PlayCardAction
class PlayCardCommand
class PlayCardState
class PlayableCard
class PlayedCardEvent
class Player
class PlayerBoard
class PlayerElementsEvent
class PlayerHand
enum PlayerToken << enumeration >>
class PlayerTurnEvent
enum PointsType << enumeration >>
class PopupObjective
class PopupStarter
class PopupTokens
class PostGameState
class RMIConnectionHandler
class RMIGameServer
class RMIGameView
class RMIHandler
class RMIMainServer
class RMIMainView
class ReconnectToGameEvent
class ReconnectionCommand
class ResourceCard
class ResourceDeckCreator
enum Resources << enumeration >>
class ResultsScene
class Scene
class SceneManager
class SceneNotRegisteredException
class SceneTester
class ScoreTrack
class SelectObjectiveCardCommand
class SelectStarterCardSideCommand
class SelectTokenCommand
enum Server << enumeration >>
class ServerEventHandlerTask
class ServerPrinter
class SetupPhaseController
class SlimGameModel
class SocketClientHandler
class SocketConnectionHandler
class SocketServer
class StartGameCommand
class StartGameError
class StarterCard
class StarterCardScene
class StarterCardSelectionState
class StarterDeckCreator
enum Status << enumeration >>
class TokenAssignmentEvent
class TokenSelectionScene
class TokenSelectionState
class Trio<T1, T2, T3>
interface UI << interface >>
class UpdatedScoreTrackEvent
class User
class UserInfo
class UserInfoLoginScene
class UserInfoManager
class VisibleCardsList<CardType>

AccountScene                    -[#000082,plain]-^  Scene                          
CLI                             -[#008200,dashed]-^  UI                             
CardsPlayabilityEvent           -[#000082,plain]-^  GameEvent                      
ChosenObjectiveCardEvent        -[#000082,plain]-^  GameEvent                      
ChosenStarterCardSideEvent      -[#000082,plain]-^  GameEvent                      
Client                          -[#008200,dashed]-^  GameViewActions                
Client                          -[#008200,dashed]-^  MainViewActions                
Client                          -[#008200,dashed]-^  Observer                       
ConfigController                -[#000082,plain]-^  Controller                     
ConnectionCommand               -[#000082,plain]-^  MainCommand                    
ConnectionLostScene             -[#000082,plain]-^  Scene                          
ConnectionScene                 -[#000082,plain]-^  Scene                          
Controller                      -[#008200,dashed]-^  UI                             
CreateLobbyCommand              -[#000082,plain]-^  MainCommand                    
CreateLobbyError                -[#000082,plain]-^  MainErrorEvent                 
Deck                            -[#595959,dashed]->  Card                           
Deck                            -[#000082,plain]-^  Observable                     
DirectMessageCommand            -[#000082,plain]-^  MessageCommand                 
DirectMessageEvent              -[#000082,plain]-^  MessageEvent                   
DrawCardState                   -[#000082,plain]-^  GameState                      
DrawGoldDeckCardCommand         -[#000082,plain]-^  GameCommand                    
DrawObjectiveCardsCommand       -[#000082,plain]-^  GameCommand                    
DrawResourceDeckCardCommand     -[#000082,plain]-^  GameCommand                    
DrawStarterCardCommand          -[#000082,plain]-^  GameCommand                    
DrawVisibleGoldCardCommand      -[#000082,plain]-^  GameCommand                    
DrawVisibleResourceCardCommand  -[#000082,plain]-^  GameCommand                    
DrawnGoldDeckCardEvent          -[#000082,plain]-^  GameEvent                      
DrawnObjectiveCardsEvent        -[#000082,plain]-^  GameEvent                      
DrawnResourceDeckCardEvent      -[#000082,plain]-^  GameEvent                      
DrawnStarterCardEvent           -[#000082,plain]-^  GameEvent                      
DrawnVisibleGoldCardEvent       -[#000082,plain]-^  GameEvent                      
DrawnVisibleResourceCardEvent   -[#000082,plain]-^  GameEvent                      
EndedInitializationPhaseEvent   -[#000082,plain]-^  GameEvent                      
EndedObjectiveCardPhaseEvent    -[#000082,plain]-^  GameEvent                      
EndedStarterCardPhaseEvent      -[#000082,plain]-^  GameEvent                      
EndedTokenPhaseEvent            -[#000082,plain]-^  GameEvent                      
EndingGameInitScene             -[#000082,plain]-^  GameScene                      
GameCommand                     -[#000082,plain]-^  Command                        
GameController                  -[#000082,plain]-^  Controller                     
GameErrorEvent                  -[#000082,plain]-^  GameEvent                      
GameEvent                       -[#000082,plain]-^  Event                          
GameResultsEvent                -[#000082,plain]-^  GameEvent                      
GameScene                       -[#000082,plain]-^  Scene                          
GameStartedEvent                -[#000082,plain]-^  MainEvent                      
GoldCard                        -[#000082,plain]-^  PlayableCard                   
GroupMessageCommand             -[#000082,plain]-^  MessageCommand                 
GroupMessageEvent               -[#000082,plain]-^  MessageEvent                   
HomeScene                       -[#000082,plain]-^  Scene                          
InitializationState             -[#000082,plain]-^  GameState                      
Items                           -[#008200,dashed]-^  Elements                       
ItemsObjectiveStrategy          -[#008200,dashed]-^  ObjectiveStrategy              
JoinLobbyCommand                -[#000082,plain]-^  MainCommand                    
JoinLobbyController             -[#000082,plain]-^  Controller                     
JoinLobbyError                  -[#000082,plain]-^  MainErrorEvent                 
KeepAliveCommand                -[#000082,plain]-^  MainCommand                    
KeepAliveEvent                  -[#000082,plain]-^  MainEvent                      
LastConnectedPlayerEvent        -[#000082,plain]-^  GameEvent                      
LastConnectedPlayerWonEvent     -[#000082,plain]-^  GameEvent                      
LastPlayerScene                 -[#000082,plain]-^  Scene                          
LastPlayerWonScene              -[#000082,plain]-^  Scene                          
LastRoundEvent                  -[#000082,plain]-^  GameEvent                      
LeaveLobbyCommand               -[#000082,plain]-^  MainCommand                    
LeaveLobbyError                 -[#000082,plain]-^  MainErrorEvent                 
LobbiesEvent                    -[#000082,plain]-^  MainEvent                      
LobbiesListController           -[#000082,plain]-^  Controller                     
LobbiesScene                    -[#000082,plain]-^  Scene                          
LobbyController                 -[#000082,plain]-^  Controller                     
LoginEvent                      -[#000082,plain]-^  MainEvent                      
MainCommand                     -[#000082,plain]-^  Command                        
MainController                  -[#000082,plain]-^  Controller                     
MainErrorEvent                  -[#000082,plain]-^  MainEvent                      
MainEvent                       -[#000082,plain]-^  Event                          
MenuController                  -[#000082,plain]-^  Controller                     
MessageCommand                  -[#000082,plain]-^  GameCommand                    
MessageEvent                    -[#000082,plain]-^  GameEvent                      
ObjectiveCard                   -[#000082,plain]-^  Card                           
ObjectiveCardScene              -[#000082,plain]-^  Scene                          
ObjectiveCardSelectionState     -[#000082,plain]-^  GameState                      
PatternObjectiveStrategy        -[#008200,dashed]-^  ObjectiveStrategy              
PlayCardCommand                 -[#000082,plain]-^  GameCommand                    
PlayCardState                   -[#000082,plain]-^  GameState                      
PlayableCard                    -[#000082,plain]-^  Card                           
PlayedCardEvent                 -[#000082,plain]-^  GameEvent                      
PlayerBoard                     -[#000082,plain]-^  Observable                     
PlayerElementsEvent             -[#000082,plain]-^  GameEvent                      
PlayerTurnEvent                 -[#000082,plain]-^  GameEvent                      
PostGameState                   -[#000082,plain]-^  GameState                      
RMIConnectionHandler            -[#000082,plain]-^  ConnectionHandler              
RMIGameServer                   -[#008200,dashed]-^  GameServerActions              
RMIGameView                     -[#008200,dashed]-^  GameViewActions                
RMIHandler                      -[#000082,plain]-^  Client                         
RMIMainServer                   -[#008200,dashed]-^  MainServerActions              
RMIMainView                     -[#008200,dashed]-^  MainViewActions                
ReconnectToGameEvent            -[#000082,plain]-^  MainEvent                      
ReconnectionCommand             -[#000082,plain]-^  MainCommand                    
ResourceCard                    -[#000082,plain]-^  PlayableCard                   
Resources                       -[#008200,dashed]-^  Elements                       
ResultsScene                    -[#000082,plain]-^  Scene                          
ScoreTrack                      -[#000082,plain]-^  Observable                     
SelectObjectiveCardCommand      -[#000082,plain]-^  GameCommand                    
SelectStarterCardSideCommand    -[#000082,plain]-^  GameCommand                    
SelectTokenCommand              -[#000082,plain]-^  GameCommand                    
SetupPhaseController            -[#000082,plain]-^  Controller                     
SocketClientHandler             -[#000082,plain]-^  Client                         
SocketConnectionHandler         -[#000082,plain]-^  ConnectionHandler              
StartGameCommand                -[#000082,plain]-^  MainCommand                    
StartGameError                  -[#000082,plain]-^  MainErrorEvent                 
StarterCard                     -[#000082,plain]-^  PlayableCard                   
StarterCardScene                -[#000082,plain]-^  Scene                          
StarterCardSelectionState       -[#000082,plain]-^  GameState                      
TokenAssignmentEvent            -[#000082,plain]-^  GameEvent                      
TokenSelectionScene             -[#000082,plain]-^  Scene                          
TokenSelectionState             -[#000082,plain]-^  GameState                      
UI                              -[#008200,plain]-^  GameEventHandler               
UI                              -[#008200,plain]-^  MainEventHandler               
UpdatedScoreTrackEvent          -[#000082,plain]-^  GameEvent                      
UserInfoLoginScene              -[#000082,plain]-^  Scene                          
VisibleCardsList                -[#595959,dashed]->  Card                           
VisibleCardsList                -[#000082,plain]-^  Observable                     
@enduml
