@startuml

package Client {
    ' View related classes
    abstract class UI

    class GUI extends UI
    class TUI extends UI

    class View {
        - userInterface: UI
    }

    View <-- "1" UI

    class ClientController {
        - networkProtocol: ClientNetworkProtocol
    }

    ' MVC client view controller relationship

    View --> ClientController: notify user action
    ClientController --> View: update/modify view
}

package Server {

    ' This class handles the connection with the client
    class PlayerConnectionHandler {
        - playerConnection: ServerNetworkProtocol
    }

    ' Controller for a single game
    class GameController {
        - model: GameModel
        - playersConnections: ServerNetworkProtocol[]
    }

    ' MVC server controller/model relationship
    GameController --> GameModel: uses

    ' This class represents a single running game
    class Game {
        - gameController: GameController
    }

    Game --> GameController

    class GameServer {
        - games: Game[]
        - playersConnected: PlayerConnection[]
        + startServer()
        + stopServer()
        + joinGame()
    }

    GameServer "1" --> "0...N" Game

    ' TODO discuss add, remove, modify
    class GameModel {
        - players: Player[4]
        - playersSequence: Player[4]
        - id: String
        - scoreTrack: ScoreTrack
        - starterDeck: StarterDeck
        - goldCardDeck: GoldCardDeck
        - objectiveDeck: ObjectiveDeck
        - resourceCard: ResourceCard
        - turn: int
        - currentPlayer: Player
    }

    class Player

    class PlayerHand

    abstract class Card {
        ' - getFront(): CardSide
        ' - getBack(): CardSide
    }

    /' abstract class CardSide {

    }

    '/

    class ScoreTrack {
        - move(token: Token, int points): void
        - notifyLastRound(): void
    }

    class Token

    enum TokenColor {
        RED
        BLUE
        GREEN
        YELLOW
        BLACK
    }

    abstract class PlayableCard extends Card {
        - draw(): void
        - place(): void
        - corners: Corner[4]
        - color: Color
    }

    class GoldCard extends PlayableCard

    class ResourceCard extends PlayableCard

    class StarterCard extends PlayableCard


    class ObjectiveCard extends Card {
        - objective: Objective
    }

    abstract class Objective {
        - points: Points
    }

    class ResourcesObjective extends Objective {
        - color: Color
    }

    class PatternsObjective extends Objective {
        - pattern: Pattern
    }

    class ObjectsObjective extends Objective {
        /' - object: Combinations
        TODO Discuss and change type
        '/
    }

    abstract class Deck

    class StarterDeck extends Deck

    class GoldCardDeck extends Deck

    class ObjectiveDeck extends Deck

    class ResourceCardDeck extends Deck

    class DrawableVisibleCards {
        + resourceCard: ResourceCard[2]
        + goldCard: GoldCard[2]
    }

    class CommonObjectivesCards {
        + objectiveCard: ObjectiveCard[2]
    }

    enum Points {
        2, 3
    }

    enum Pattern {
        1, 2, 3, 4, 5, 6, 7, 8
        'TODO Hardcode the eight patterns
    }

    enum Combinations {
        TRIS
        QUILL
        INKWELL
        MANUSCRIPT
        'TODO Discuss with ObjectsObjective (see above)
    }


    class Corner {
        - cornerVisibility: CornerVisibility
        - cornerPosition: CornerPosition
        - cornerResourceType: CornerResourceType
        - cornerState: CornerState
    }

    enum CornerState {
        CLEAR
        COVERED
    }

    enum CornerVisibility {
        VISIBLE
        HIDDEN
    }

    enum CornerPosition {
        TOP_LEFT
        TOP_RIGHT
        BOTTOM_LEFT
        BOTTOM_RIGHT
    }

    enum Color {
        RED
        GREEN
        PURPLE
        BLUE
        ' TODO discuss about "NONE" color for starter card implementation
        NONE
    }

    enum CornerResourceType {
        PLANT
        ANIMAL
        FUNGI
        INSECT
        QUILL
        INKWELL
        MANUSCRIPT
        EMPTY
    }




    PlayableCard --> Color
    Corner --> CornerResourceType
    Corner --> CornerState
    Corner --> CornerPosition
    Corner --> CornerVisibility

    ObjectiveCard --> Objective

}

package Networking {
    ' This abstract class handles communications for the client
    abstract class ClientNetworkProtocol
    class RMIClientProtocol extends ClientNetworkProtocol
    class SocketClientProtocol extends ClientNetworkProtocol


    ' This abstract class handles communications for the server
    abstract class ServerNetworkProtocol
    class RMIServerProtocol extends ServerNetworkProtocol
    class SocketServerProtocol extends ServerNetworkProtocol
}

' Networking relations6
ClientController "0..1" <-- "1" ClientNetworkProtocol
GameController "1" <-- "1..4" ServerNetworkProtocol

' MVC client controller / server controller relation
ClientController "1" <-[#red]-> "1..4" GameController: connected
' TODO to join/create a game the client controller must connect directly to the game server

@enduml
