@startuml

package Client {
    ' View related classes
    abstract class UI

    class GUI extends UI
    class TUI extends UI

    class View {
        - userInterface: UI
    }

    View <-- "1" UI

    class ClientController {
        - networkProtocol: ClientNetworkProtocol
    }

    ' MVC client view controller relationship

    View --> ClientController: notify user action
    ClientController --> View: update/modify view
}

package Server {

    ' Controller for a single game
    class GameController {
        - model: GameModel
    }

    ' Controller for the connections in a single game
    class GameNetworkController {
        - playersConnections: ServerNetworkProtocol[]
    }

    class GameModel

    ' MVC server controller/model relationship
    GameController --> GameModel: uses

    ' This class represents a single running game
    class GameSession {
        - gameController: GameController
        - gameNetworkController: GameNetworkController
    }

    GameSession --> GameController
    GameSession --> GameNetworkController

    ' The game server keeps a pool of connected users and can start games on users' requests
    class GameServer {
        - playersConnections: ClientNetworkProtocol[]
        - games: Game[]
        + startServer()
        + stopServer()
        + joinGame()
    }

    GameServer "1" --> "0...N" GameSession
}

package Networking {
    ' This abstract class handles communications for the client
    abstract class ClientNetworkProtocol
    class RMIClient extends ClientNetworkProtocol
    class SocketClient extends ClientNetworkProtocol


    ' This abstract class handles communications for the server
    abstract class ServerNetworkProtocol
    class RMIServer extends ServerNetworkProtocol
    class SocketServer extends ServerNetworkProtocol
}

' Networking relations
ClientController "0..1" <-- "1" ClientNetworkProtocol
GameController "1" <-- "1..4" ServerNetworkProtocol

' MVC client controller / game network controller relation
ClientController "1..4" <-[#red]-> "1" GameNetworkController: connected

' MVC client controller / server controller relation
ClientController "1..*" <-[#red]-> "1" GameServer: connected

@enduml
