@startuml

participant VirtualMainView #white
participant VirtualMainServer #yellow

VirtualMainView -> VirtualMainServer: connect(this, currentUser)
VirtualMainServer -> VirtualMainView: sendLobbies(): []
VirtualMainView -> VirtualMainServer: send(new JoinLobbyCommand(1))
VirtualMainServer -> VirtualMainView: sendError("Invalid lobby id")
VirtualMainView -> VirtualMainServer: send(new CreateLobbyCommand)
VirtualMainServer -> VirtualMainView: sendLobbies(): [(id: 1, manager: currentUser, users: [currentUser], gamestarted: false)]
note over VirtualMainServer: anotherUser joins the lobby
VirtualMainServer -> VirtualMainView: sendLobbies(): [(id: 1, manager: currentUser, users: [currentUser, anotherUser], gamestarted: false)]
VirtualMainView -> VirtualMainServer: joinGame(currentUser): connectionInfo
VirtualMainServer -> VirtualMainView: sendLobbies(): [(id: 1, manager: currentUser, users: [currentUser, anotherUser], gamestarted: true)]
note across: the user can now open the game connection with the information in the received connectionInfo object
@enduml